on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build and push a docker image

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAWGTBCUPCHPTTBGHW
        aws-secret-access-key: 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
        aws-region: eu-west-3
        
   # Deploy to aws
    #
    - name: Deploy to aws
      run: aws eks update-kubeconfig --region eu-west-3 --name eks_cluster_tuto
      run: kubectl apply -f vuejs-deployment.yaml
